"""rename type to payment_type

Revision ID: 0c965d549c30
Revises: e6a978c2be13
Create Date: 2025-11-23 13:53:04.929710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c965d549c30'
down_revision = 'e6a978c2be13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=10), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
