"""Add saree_name and saree_type to Loom

Revision ID: 104463b6252c
Revises: 4be4de381865
Create Date: 2025-09-19 17:57:47.190270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104463b6252c'
down_revision = '4be4de381865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saree_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_column('saree_name')

    # ### end Alembic commands ###
