"""Remove weaver_name column from looms

Revision ID: 19ba3a53fbec
Revises: ccb445b69b7f
Create Date: 2025-11-23 20:33:13.790682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ba3a53fbec'
down_revision = 'ccb445b69b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_column('weaver_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaver_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
