"""initial

Revision ID: 27ffd37a0135
Revises: 
Create Date: 2025-11-25 07:48:51.711053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ffd37a0135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('weavers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weavername', sa.String(length=100), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('name_in_bank', sa.String(length=100), nullable=True),
    sa.Column('aadharcard', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_credit', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weavers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weavers_user_id'), ['user_id'], unique=False)

    op.create_table('looms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_no', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weaver_id', sa.Integer(), nullable=True),
    sa.Column('loom_type', sa.String(length=50), nullable=False),
    sa.Column('num_sarees', sa.Integer(), nullable=False),
    sa.Column('saree_type', sa.String(length=50), nullable=True),
    sa.Column('saree_name', sa.String(length=100), nullable=True),
    sa.Column('amount_credit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_debit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weaver_id'], ['weavers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_looms_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_looms_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_looms_user_id'), ['user_id'], unique=False)

    op.create_table('saree_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saree_number', sa.Integer(), nullable=True),
    sa.Column('saree_name', sa.String(length=100), nullable=True),
    sa.Column('saree_image', sa.String(length=200), nullable=True),
    sa.Column('colors', sa.String(length=200), nullable=True),
    sa.Column('warp_weft', sa.String(length=100), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('border_color', sa.String(length=100), nullable=True),
    sa.Column('border_hex', sa.String(length=10), nullable=True),
    sa.Column('body_color', sa.String(length=100), nullable=True),
    sa.Column('body_hex', sa.String(length=10), nullable=True),
    sa.Column('meena_a', sa.String(length=100), nullable=True),
    sa.Column('meena_a_hex', sa.String(length=10), nullable=True),
    sa.Column('meena_b', sa.String(length=100), nullable=True),
    sa.Column('meena_b_hex', sa.String(length=10), nullable=True),
    sa.Column('meena_c', sa.String(length=100), nullable=True),
    sa.Column('meena_c_hex', sa.String(length=10), nullable=True),
    sa.Column('meena_d', sa.String(length=100), nullable=True),
    sa.Column('meena_d_hex', sa.String(length=10), nullable=True),
    sa.Column('amount_credit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_debit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saree_entries_loom_id'), ['loom_id'], unique=False)

    op.create_table('warp_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('border_color', sa.String(length=100), nullable=True),
    sa.Column('body_color', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('zari_border_left', sa.String(length=100), nullable=True),
    sa.Column('zari_border_right', sa.String(length=100), nullable=True),
    sa.Column('zari_body', sa.String(length=100), nullable=True),
    sa.Column('silk_border_left', sa.String(length=100), nullable=True),
    sa.Column('silk_border_right', sa.String(length=100), nullable=True),
    sa.Column('silk_body', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weft_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('no_of_sarees', sa.Integer(), nullable=False),
    sa.Column('border_weft', sa.String(length=100), nullable=False),
    sa.Column('body_weft', sa.String(length=100), nullable=False),
    sa.Column('meena_a', sa.String(length=100), nullable=True),
    sa.Column('meena_b', sa.String(length=100), nullable=True),
    sa.Column('meena_c', sa.String(length=100), nullable=True),
    sa.Column('meena_d', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wefts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('zari', sa.String(length=100), nullable=True),
    sa.Column('silk', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.String(length=10), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=True),
    sa.Column('saree_id', sa.Integer(), nullable=True),
    sa.Column('weaver_id', sa.Integer(), nullable=True),
    sa.Column('name_in_bank', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.ForeignKeyConstraint(['saree_id'], ['saree_entries.id'], ),
    sa.ForeignKeyConstraint(['weaver_id'], ['weavers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('wefts')
    op.drop_table('weft_colors')
    op.drop_table('warps')
    op.drop_table('warp_colors')
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saree_entries_loom_id'))

    op.drop_table('saree_entries')
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_looms_user_id'))
        batch_op.drop_index(batch_op.f('ix_looms_date'))
        batch_op.drop_index(batch_op.f('ix_looms_created_at'))

    op.drop_table('looms')
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weavers_user_id'))
        batch_op.drop_index(batch_op.f('ix_weavers_created_at'))

    op.drop_table('weavers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
