"""Add saree_type to Loom

Revision ID: 4be4de381865
Revises: 792cb3599517
Create Date: 2025-09-19 17:55:55.900541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be4de381865'
down_revision = '792cb3599517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.alter_column('saree_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('saree_name')

    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.alter_column('saree_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.alter_column('saree_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saree_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('saree_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
