"""empty message

Revision ID: 526c56147346
Revises: baef0d7aa20b
Create Date: 2025-11-22 19:45:32.717934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '526c56147346'
down_revision = 'baef0d7aa20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('loom_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saree_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('loom_type')
        batch_op.drop_column('loom_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loom_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('loom_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('saree_id')
        batch_op.drop_column('loom_id')
        batch_op.drop_column('type')
        batch_op.drop_column('description')

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('loom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_pkey'))
    )
    # ### end Alembic commands ###
