"""Add zari/silk fields to Warp

Revision ID: 630d98a21b98
Revises: 91d28926090b
Create Date: 2025-10-10 22:00:08.958845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630d98a21b98'
down_revision = '91d28926090b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('zari_border_left', sa.String(length=100), nullable=True),
    sa.Column('zari_border_right', sa.String(length=100), nullable=True),
    sa.Column('zari_body', sa.String(length=100), nullable=True),
    sa.Column('silk_border_left', sa.String(length=100), nullable=True),
    sa.Column('silk_border_right', sa.String(length=100), nullable=True),
    sa.Column('silk_body', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('warp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('loom_id', sa.INTEGER(), nullable=False),
    sa.Column('yarn_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=50), nullable=False),
    sa.Column('count', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ends', sa.INTEGER(), nullable=False),
    sa.Column('reed', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pick', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('warps')
    # ### end Alembic commands ###
