"""add weft model

Revision ID: 69150f5db098
Revises: a4eb683980af
Create Date: 2025-10-15 12:31:08.851841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69150f5db098'
down_revision = 'a4eb683980af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wefts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('zari', sa.String(length=100), nullable=True),
    sa.Column('silk', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wefts')
    # ### end Alembic commands ###
