"""Add total_credit to Weaver

Revision ID: 6c792e1a4b5e
Revises: 104463b6252c
Create Date: 2025-10-05 10:15:19.308508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c792e1a4b5e'
down_revision = '104463b6252c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_credit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.drop_column('total_credit')

    # ### end Alembic commands ###
