"""Add WarpColor model

Revision ID: 8d316d084a30
Revises: 69150f5db098
Create Date: 2025-10-15 13:26:59.015105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d316d084a30'
down_revision = '69150f5db098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warp_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('border_color', sa.String(length=100), nullable=True),
    sa.Column('body_color', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warp_colors')
    # ### end Alembic commands ###
