"""Add payments FK and relationships

Revision ID: 8dc749b2fff4
Revises: 767f2e4e4d84
Create Date: 2025-11-22 20:05:56.747602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc749b2fff4'
down_revision = '767f2e4e4d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_loom_id'), ['loom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_saree_id'), ['saree_id'], unique=False)
        batch_op.create_foreign_key(None, 'saree_entries', ['saree_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_saree_id'))
        batch_op.drop_index(batch_op.f('ix_payments_loom_id'))

    # ### end Alembic commands ###
