"""fixed foreign key from warp to looms

Revision ID: 91d28926090b
Revises: fffcaffe2adc
Create Date: 2025-10-10 21:52:59.573083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d28926090b'
down_revision = 'fffcaffe2adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('yarn_type', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('count', sa.String(length=50), nullable=False),
    sa.Column('ends', sa.Integer(), nullable=False),
    sa.Column('reed', sa.String(length=50), nullable=True),
    sa.Column('pick', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_created_at'))
        batch_op.drop_index(batch_op.f('ix_materials_date'))
        batch_op.drop_index(batch_op.f('ix_materials_user_id'))

    op.drop_table('materials')
    with op.batch_alter_table('warps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warps_created_at'))
        batch_op.drop_index(batch_op.f('ix_warps_user_id'))

    op.drop_table('warps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bordersilk', sa.VARCHAR(length=100), nullable=False),
    sa.Column('body_silk', sa.VARCHAR(length=100), nullable=False),
    sa.Column('border_zari', sa.VARCHAR(length=100), nullable=False),
    sa.Column('body_zari', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warps_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warps_created_at'), ['created_at'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('silk_material', sa.VARCHAR(length=100), nullable=False),
    sa.Column('zari_silver', sa.VARCHAR(length=100), nullable=False),
    sa.Column('zari_gold', sa.VARCHAR(length=100), nullable=False),
    sa.Column('extra', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_created_at'), ['created_at'], unique=False)

    op.drop_table('warp')
    # ### end Alembic commands ###
