"""Add name_in_bank column

Revision ID: 9d9242841a82
Revises: ee77f5c8628d
Create Date: 2025-11-23 16:15:17.020391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9242841a82'
down_revision = 'ee77f5c8628d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_in_bank', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('name_in_bank')

    # ### end Alembic commands ###
