"""Add meena color fields to saree_entries

Revision ID: a4eb683980af
Revises: 630d98a21b98
Create Date: 2025-10-14 11:48:55.540179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4eb683980af'
down_revision = '630d98a21b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('body_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('meena_a', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meena_a_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('meena_b', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meena_b_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('meena_c', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meena_c_hex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('meena_d', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meena_d_hex', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.drop_column('meena_d_hex')
        batch_op.drop_column('meena_d')
        batch_op.drop_column('meena_c_hex')
        batch_op.drop_column('meena_c')
        batch_op.drop_column('meena_b_hex')
        batch_op.drop_column('meena_b')
        batch_op.drop_column('meena_a_hex')
        batch_op.drop_column('meena_a')
        batch_op.drop_column('body_hex')
        batch_op.drop_column('border_hex')

    # ### end Alembic commands ###
