"""Added WeftColor

Revision ID: b4244256f103
Revises: 19ba3a53fbec
Create Date: 2025-11-24 11:31:50.290464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4244256f103'
down_revision = '19ba3a53fbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weft_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loom_id', sa.Integer(), nullable=False),
    sa.Column('no_of_sarees', sa.Integer(), nullable=False),
    sa.Column('border_weft', sa.String(length=100), nullable=False),
    sa.Column('body_weft', sa.String(length=100), nullable=False),
    sa.Column('meena_a', sa.String(length=100), nullable=True),
    sa.Column('meena_b', sa.String(length=100), nullable=True),
    sa.Column('meena_c', sa.String(length=100), nullable=True),
    sa.Column('meena_d', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loom_id'], ['looms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weft_colors')
    # ### end Alembic commands ###
