"""Added bank details to Weaver

Revision ID: baef0d7aa20b
Revises: dd124dae9b71
Create Date: 2025-11-22 13:27:06.628912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baef0d7aa20b'
down_revision = 'dd124dae9b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_in_bank', sa.String(length=100), nullable=True))
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_column('bank_holder_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('name_in_bank')

    # ### end Alembic commands ###
