"""Fix payment model + add name_in_bank

Revision ID: ccb445b69b7f
Revises: 9d9242841a82
Create Date: 2025-11-23 17:18:44.818870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb445b69b7f'
down_revision = '9d9242841a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaver_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('name_in_bank',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'looms', ['loom_id'], ['id'])
        batch_op.create_foreign_key(None, 'weavers', ['weaver_id'], ['id'])
        batch_op.create_foreign_key(None, 'saree_entries', ['saree_id'], ['id'])
        batch_op.drop_column('account_no')
        batch_op.drop_column('description')
        batch_op.drop_column('account_name')
        batch_op.drop_column('loom_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loom_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('account_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name_in_bank',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('account_number')
        batch_op.drop_column('weaver_id')

    # ### end Alembic commands ###
