"""Add Notification model

Revision ID: ceeae4816756
Revises: def700efc117
Create Date: 2025-11-04 12:47:24.081061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeae4816756'
down_revision = 'def700efc117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
