"""Add border_color and body_color to saree_entries

Revision ID: d649e8fa24a4
Revises: 6c792e1a4b5e
Create Date: 2025-10-05 15:32:48.182695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd649e8fa24a4'
down_revision = '6c792e1a4b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_color', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('body_color', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_column('body_color')
        batch_op.drop_column('border_color')

    # ### end Alembic commands ###
