"""Added bank details to weavers

Revision ID: dd124dae9b71
Revises: 5fa4d470b782
Create Date: 2025-11-22 13:17:32.131318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd124dae9b71'
down_revision = '5fa4d470b782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_holder_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weavers', schema=None) as batch_op:
        batch_op.drop_column('bank_holder_name')
        batch_op.drop_column('account_type')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###
