"""add loom_type to payments

Revision ID: e6a978c2be13
Revises: 8dc749b2fff4
Create Date: 2025-11-23 13:46:45.852083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a978c2be13'
down_revision = '8dc749b2fff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loom_type', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_payments_loom_id'))
        batch_op.drop_index(batch_op.f('ix_payments_saree_id'))
        batch_op.drop_constraint(batch_op.f('payments_saree_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_loom_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('payments_loom_id_fkey'), 'looms', ['loom_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('payments_saree_id_fkey'), 'saree_entries', ['saree_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_payments_saree_id'), ['saree_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_loom_id'), ['loom_id'], unique=False)
        batch_op.drop_column('loom_type')

    # ### end Alembic commands ###
