"""add loom_type

Revision ID: ee77f5c8628d
Revises: 0c965d549c30
Create Date: 2025-11-23 15:59:32.965867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee77f5c8628d'
down_revision = '0c965d549c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_no')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
