"""Added border_color and body_color columns

Revision ID: fffcaffe2adc
Revises: d649e8fa24a4
Create Date: 2025-10-05 15:36:20.135355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffcaffe2adc'
down_revision = 'd649e8fa24a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.drop_column('body_color')
        batch_op.drop_column('border_color')

    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_color', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('body_color', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saree_entries', schema=None) as batch_op:
        batch_op.drop_column('body_color')
        batch_op.drop_column('border_color')

    with op.batch_alter_table('looms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('border_color', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('body_color', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
